name: Build wxMMDViewer

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master


jobs:
  build:
    runs-on: ubuntu-latest # focal

    steps:
    - name: Checkout source
      uses: actions/checkout@v6
      with:
        submodules: recursive


    - name: Update packages
      run: sudo apt-get update -y

    - name: Install build tools
      run: sudo apt-get install -y libwxgtk3.2-dev libssl-dev freeglut3-dev zlib1g-dev curl default-jre libglew-dev libglm-dev ninja-build

    - name: Install Kaitai Struct
      run: |
        curl -LO https://github.com/kaitai-io/kaitai_struct_compiler/releases/download/0.11/kaitai-struct-compiler_0.11_all.deb
        sudo apt-get install -y ./kaitai-struct-compiler_0.11_all.deb

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G Ninja

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: ninja && ninja package

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: wxmmdviewer-deb
        path: build/*.deb

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -V
