name: Build wxMMDViewer

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    runs-on: ubuntu-latest # focal

    steps:
    - name: Checkout source
      uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: install-cmake
      uses: Symbitic/install-cmake@v0.1.0
      with:
        cmake: 3.17.2
        ninja: 1.9.0

    - name: Update packages
      run: sudo apt-get update -y

    - name: Install build tools
      run: sudo apt-get install -y libwxgtk3.2-dev libssl-dev freeglut3-dev zlib1g-dev curl default-jre libglew-dev libglm-dev

    - name: Install Kaitai Struct
      run: |
        curl -LO https://github.com/kaitai-io/kaitai_struct_compiler/releases/download/0.11/kaitai-struct-compiler_0.11_all.deb
        sudo apt-get install -y ./kaitai-struct-compiler_0.11_all.deb

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G Ninja

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: ninja && ninja package

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -V
