name: Release wxMMDViewer

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v6
      with:
        submodules: recursive


    - name: Update packages
      run: sudo apt-get update -y

    - name: Install build tools
      run: sudo apt-get install -y libwxgtk3.2-dev libssl-dev freeglut3-dev zlib1g-dev curl default-jre libglew-dev libglm-dev ninja-build

    - name: Install Kaitai Struct
      run: |
        curl -LO https://github.com/kaitai-io/kaitai_struct_compiler/releases/download/0.11/kaitai-struct-compiler_0.11_all.deb
        sudo apt-get install -y ./kaitai-struct-compiler_0.11_all.deb

    - name: Configure CMake
      run: cmake -B build -G Ninja

    - name: Build and Package
      working-directory: build
      run: ninja && ninja package

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: build/*.deb
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
